### Read all pizzas
GET http://localhost:3000/taches

### read all task
@baseUrl = http://localhost:3000
GET {{baseUrl}}/taches/

### Create a task
POST {{baseUrl}}/taches/
Content-Type: application/json

{
    "title":"on est conAAA ? ",
    "content":"AA112211A de test",
    "difficulte":"3"
}


### Remove a task with the Task ID
DELETE {{baseUrl}}/taches/1

### Display a specific task with the Task ID
GET {{baseUrl}}/taches/fd11d28a-4469-433d-a4d1-56f46f52dd11

