### Read all pizzas
GET http://localhost:3000/taches

### read all task
@baseUrl = http://localhost:3000
GET {{baseUrl}}/taches/

### Create a task
POST {{baseUrl}}/taches/
Content-Type: application/json

{
    "title":"raphael ? ",
    "content":"AA112211A rgrg test",
    "difficulte":"3"
}


### Remove a task with the Task ID
DELETE {{baseUrl}}/taches/0394347f-d18d-40ce-a803-9985d4a05d2a

### Display a specific task with the Task ID
GET {{baseUrl}}/taches/6af259a8-23e1-465b-83af-f56b4560d20f

### Valide a Task with the Task ID
POST {{baseUrl}}/taches/valide/4c1115e2-6d8a-4f72-a378-a4063a43f1d8
