### Read all pizzas
GET http://localhost:3000/taches

### read all task
@baseUrl = http://localhost:3000
GET {{baseUrl}}/taches/

### Create a task
POST {{baseUrl}}/taches/
Content-Type: application/json

{
    "title":"tache de test titre",
    "content":"tache de test",
    "difficulte":"1"
}


### Remove a task with the Task ID
DELETE {{baseUrl}}/taches/1

### Display a specific task with the Task ID
GET {{baseUrl}}/taches/1

