
### read all task
@baseUrl = http://localhost:3000
GET {{baseUrl}}/

### Create a user
POST {{baseUrl}}/auths/
Content-Type: application/json

{
    "username": "testa",
    "password": "test"
}

### Remove a task with the Task ID
DELETE {{baseUrl}}/taches/1
